export enum RolePermissionKey {
  UserList = 'user.list',
  UserRead = 'user.read',
  UserUpdate = 'user.update',
  UserDelete = 'user.delete',
  RoleList = 'role.list',
  RoleRead = 'role.read',
  RoleCreate = 'role.create',
  RoleUpdate = 'role.update',
  RoleUserUpdate = 'role.user.update',
  RolePermissionUpdate = 'role.permission.update',
  RoleDelete = 'role.delete',
  PartnerGroupList = 'partner-group.list',
  PartnerGroupRead = 'partner-group.read',
  PartnerGroupCreate = 'partner-group.create',
  PartnerGroupUpdate = 'partner-group.update',
  PartnerGroupPartnerUpdate = 'partner-group.partner.update',
  PartnerGroupDelete = 'partner-group.delete',
  PartnerList = 'partner.list',
  PartnerRead = 'partner.read',
  PartnerCreate = 'partner.create',
  PartnerUpdate = 'partner.update',
  PartnerUserUpdate = 'partner.user.update',
  PartnerDelete = 'partner.delete',
  FulfillmentGroupList = 'fulfillment-group.list',
  FulfillmentGroupRead = 'fulfillment-group.read',
  FulfillmentGroupCreate = 'fulfillment-group.create',
  FulfillmentGroupUpdate = 'fulfillment-group.update',
  FulfillmentGroupFulfillmentUpdate = 'fulfillment-group.fulfillment.update',
  FulfillmentGroupDelete = 'fulfillment-group.delete',
  FulfillmentList = 'fulfillment.list',
  FulfillmentRead = 'fulfillment.read',
  FulfillmentCreate = 'fulfillment.create',
  FulfillmentUpdate = 'fulfillment.update',
  FulfillmentUserUpdate = 'fulfillment.user.update',
  FulfillmentDelete = 'fulfillment.delete',
}

export enum RoleSearchKeywordField {
  Name = 'name',
}
